<a href="https://colab.research.google.com/github/Deborshi18/Neural-Network/blob/master/ANN.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
#Part 1 Data Preprocessing

#Importing the libraries

import numpy as np
import matplotlib.pyplot as plt
import pandas as pd



In [0]:
#Importing the dataset

dataset=pd.read_csv("/content/sample_data/Churn_Modelling.csv")
x=dataset.iloc[:,3:13].values
y=dataset.iloc[:,13].values
 

In [0]:
x.shape

(10000, 10)

In [0]:
#Ecncoding categorical data
from sklearn.preprocessing import LabelEncoder, OneHotEncoder
labelencoder_x_1 = LabelEncoder()
x[:,1]=labelencoder_x_1.fit_transform(x[:,1])
labelencoder_x_2 = LabelEncoder()
x[:,2]=labelencoder_x_2.fit_transform(x[:,2])




In [0]:
#Splitting the dataset into the training and test set
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=0)

In [0]:
#feature scaling
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
x_train=sc.fit_transform(x_train)
x_test=sc.transform(x_test)

In [0]:
x_train.shape

(8000, 10)

In [0]:
x_test

array([[-0.56129438,  0.28034192, -1.11339196, ...,  0.66011376,
         0.97628121,  1.62185911],
       [-1.33847768, -0.93853599, -1.11339196, ...,  0.66011376,
        -1.02429504,  0.504204  ],
       [ 0.58347561,  1.49921982, -1.11339196, ...,  0.66011376,
         0.97628121, -0.41865644],
       ...,
       [-0.76084144,  1.49921982,  0.8981563 , ...,  0.66011376,
        -1.02429504,  0.72775202],
       [-0.0046631 ,  0.28034192,  0.8981563 , ...,  0.66011376,
         0.97628121, -1.54162886],
       [-0.81335383,  0.28034192,  0.8981563 , ...,  0.66011376,
        -1.02429504,  1.62356528]])

In [0]:
#ANN
import keras


In [0]:
from keras.models import Sequential
from keras.layers import Dense

In [0]:
#Initializing the ANN
classifier = Sequential()

#Adding the input layer and first hidden layer
classifier.add(Dense(units=6,kernel_initializer='uniform',activation='relu',input_dim=10))
#adding the second layer
classifier.add(Dense(units=6,kernel_initializer='uniform',activation='relu'))
#adding the output layer
classifier.add(Dense(units=1,kernel_initializer='uniform',activation='sigmoid'))



In [0]:
#compiling the ANN
classifier.compile(optimizer='adam',loss='binary_crossentropy',metrics=['accuracy'])


In [0]:
#fitting the ann to dataset
classifier.fit(x_train,y_train,batch_size=11,epochs=100)




Epoch 1/100





8000/8000 [==============================] - 12s 1ms/step - loss: 0.5041 - acc: 0.7953
Epoch 2/100
8000/8000 [==============================] - 2s 291us/step - loss: 0.4339 - acc: 0.7960
Epoch 3/100
8000/8000 [==============================] - 2s 295us/step - loss: 0.4302 - acc: 0.7960
Epoch 4/100
8000/8000 [==============================] - 2s 292us/step - loss: 0.4264 - acc: 0.7960
Epoch 5/100
8000/8000 [==============================] - 2s 293us/step - loss: 0.4231 - acc: 0.8171
Epoch 6/100
8000/8000 [==============================] - 2s 296us/step - loss: 0.4213 - acc: 0.8261
Epoch 7/100
8000/8000 [==============================] - 2s 295us/step - loss: 0.4191 - acc: 0.8289
Epoch 8/100
8000/8000 [==============================] - 2s 298us/step - loss: 0.4172 - acc: 0.8308
Epoch 9/100
8000/8000 [==============================] - 2s 291us/step - loss: 0.4163 - acc: 0.8311
Epoch 10/100
8000/8000 [==============================] - 2s 294us/step - loss: 0.4149 - acc:

In [0]:
y_pred = classifier.predict(x_test)

In [0]:
y_pred=(y_pred>0.5)

In [0]:
y_pred

array([[False],
       [False],
       [False],
       ...,
       [False],
       [False],
       [False]])

In [0]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test,y_pred)

In [0]:
cm

array([[1528,   67],
       [ 243,  162]])